[package]
name = "zero2prod"
version = "0.1.0"
authors = ["zhengpanone <zhengpanone@hotmail.com>"]
edition = "2021"


[dependencies]
axum = { version = "0.7.4", features = ["default"] }
tokio = { version = "1.36.0", features = ["full"] }

