[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
description = "A Rust project"
authors = ["zhengpanone <<zhengpanone@hotmail.com>>"]
repository = "https://github.com/zhengpanone/zero2prod"
readme = "README.md"
# # ⚡ License information for cargo-deny 声明许可协议
license = "MIT OR Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web Framework
axum = { version = "0.8.6", features = [
    "tokio",
    "http1",
    "http2",
    "macros",
    "json",
] }
tokio = { version = "1.48.0", features = ["full"] } #异步运行时
tower = { version = "0.5.2", features = ["util", "limit", "timeout"] }
tower-http = { version = "0.6.6", features = [
    "trace",
    "cors",
    "compression-full",
    "request-id",
] }

# 序列化
serde = { version = "1.0.228", features = ["derive"] } # 序列化
serde_json = "1.0.145"

# Tracing & Logging
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "fmt",
    "json",
] }

# Error Handling                                                      # 结构化日志
anyhow = "1.0.94"
thiserror = "2.0.17"

# Utilities
chrono = { version = "0.4.42", features = ["serde"] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }
validator = { version = "0.20.0", features = ["derive"] }

# API Documentation
utoipa = { version = "5.4.0", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
utoipa-axum = { version = "0.2.0" }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }

# Database
sqlx = { version = "0.8.6", features = [
    "runtime-tokio-rustls", # Tokio异步运行时
    "postgres",             # PostgreSQL数据库支持
    "macros",               # 编译时SQL验证
    "migrate",
    "uuid",                 # UUID类型支持
    "chrono",               # 日期时间支持
] }
# migrate 特性是必须启用的，否则 sqlx::migrate!() 宏会被编译为空。
# sqlx 必须启用 uuid + chrono，否则不会自动实现 FromRow

# Configuration
dotenvy = "0.15.7"
argon2 = "0.5.3"
jsonwebtoken = { version = "10.0.0", features = ["rust_crypto"] }
bcrypt = "0.17.1"
governor = "0.10.1"
futures = "0.3.31"
http-body-util = "0.1.3"
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"
