### 健康检查
GET http://localhost:3000/health HTTP/1.1

### 创建用户
POST http://localhost:3000/api/user/create HTTP/1.1
content-type: application/json

{
  "password": "admin124",
  "username": "Alice",
  "email": "Alice@example.com"
}

### 查看用户列表
GET http://localhost:3000/api/user/list HTTP/1.1
