name: Cross Build

on:
  workflow_run:
    workflows: ["CI Test"] # 必须和 ci-test.yaml 的 name 完全匹配
    types:
      - completed # 监听 CI Test 完成，无论成功或失败
    branches:
      - master
      - dev

permissions:
  contents: read # 允许 checkout 仓库

jobs:
  cross-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # 仅在 CI Test 成功时执行
    steps:
      - uses: actions/checkout@v3
      - name: Install cross
        run: cargo install cross

      - name: Build Linux x86_64
        run: cross build --release --target x86_64-unknown-linux-gnu

      - name: Build Linux ARM64
        run: cross build --release --target aarch64-unknown-linux-gnu

      - name: Build Windows x86_64
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Build macOS x86_64
        run: cross build --release --target x86_64-apple-darwin

      - name: Build macOS ARM64
        run: cross build --release --target aarch64-apple-darwin

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: rust-binaries
          path: |
            target/x86_64-unknown-linux-gnu/release/zero2prod
            target/aarch64-unknown-linux-gnu/release/zero2prod
            target/x86_64-pc-windows-gnu/release/zero2prod.exe
            target/x86_64-apple-darwin/release/zero2prod
            target/aarch64-apple-darwin/release/zero2prod
